// Auto-generated configuration file
// This file is generated by scripts/build-frontend.js
// Do not edit manually - your changes will be overwritten

// Frontend configuration
// This configuration is used by the client-side JavaScript

const CONFIG = {
    // Contract configuration
    "CONTRACT_ADDRESS": "0x56eb32579d0de82027bFD0351ac954088D66C98A",
    "NETWORK": "somnia-testnet",
    
    // API configuration - use relative URLs so it works with any deployment
    "API_BASE_URL": window.location.origin,
    
    // Network configuration
    "RPC_URL": "https://dream-rpc.somnia.network",
    "CHAIN_ID": "0x7a69", // 31337 in hex for Somnia testnet
    
    // Contract ABI
    "CONTRACT_ABI": [
        {
            "inputs": [],
            "name": "increment",
            "outputs": [],
            "stateMutability": "nonpayable",
            "type": "function"
        },
        {
            "inputs": [
                {
                    "internalType": "address",
                    "name": "user",
                    "type": "address"
                }
            ],
            "name": "getCounter",
            "outputs": [
                {
                    "internalType": "uint256",
                    "name": "",
                    "type": "uint256"
                }
            ],
            "stateMutability": "view",
            "type": "function"
        },
        {
            "anonymous": false,
            "inputs": [
                {
                    "indexed": true,
                    "internalType": "address",
                    "name": "user",
                    "type": "address"
                },
                {
                    "indexed": false,
                    "internalType": "uint256",
                    "name": "newCount",
                    "type": "uint256"
                },
                {
                    "indexed": false,
                    "internalType": "uint256",
                    "name": "timestamp",
                    "type": "uint256"
                }
            ],
            "name": "CounterIncremented",
            "type": "event"
        }
    ]
};

// Export for use in other files
window.CONFIG = CONFIG;
